spring.application.name=taskboard

spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard
spring.datasource.username=taskboard
spring.datasource.password=taskboard

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
